name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env: 
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }} 
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: cypress-io/github-action@v5
        with:
          node-version: "16"
      - run: npm install
      - run: npm run prisma:migrate:deploy && npm run prisma:seed && npx jest --detectOpenHandles && node ./prisma/utils/cleardb.js
      - run: npm run start && npm run test:cypress 
